apiVersion: v1
kind: Service
metadata:
  labels:
    app: ai-backend
  name: ai-backend-service
  namespace: default
spec:
  clusterIP: 10.96.131.102
  clusterIPs:
  - 10.96.131.102
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31818
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ai-backend
  sessionAffinity: None
  type: NodePort

