apiVersion: v1
kind: Service
metadata:
  name: ai-backend-service
  namespace: default
  labels:
    app: ai-backend
spec:
  type: ClusterIP
  selector:
    app: ai-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000